version: "3.9"
services:
  database:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: redhat
      MARIADB_DATABASE: wordpress
    volumes:
      - mariadb_volume:/var/lib/mysql

  wp:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: redhat
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8080:80"
    volumes:
      - wordpress_volume:/var/www/html

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /root/docker-webapp-compose/db
      o: bind
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /root/docker-webapp-compose/html
      o: bind

